"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * ASEvent is the superclass of all events generated by
 * the system.
 */
var ASEvent = (function () {
    function ASEvent() {
        this.time = process.hrtime ? process.hrtime() : performance ? performance.now() : new Date();
    }
    return ASEvent;
}());
exports.ASEvent = ASEvent;
/**
 * ChildSpawnedEvent
 */
var ChildSpawnedEvent = (function (_super) {
    __extends(ChildSpawnedEvent, _super);
    function ChildSpawnedEvent(address) {
        var _this = _super.call(this) || this;
        _this.address = address;
        return _this;
    }
    return ChildSpawnedEvent;
}(ASEvent));
exports.ChildSpawnedEvent = ChildSpawnedEvent;
/**
 * MessageSentEvent
 */
var MessageSentEvent = (function (_super) {
    __extends(MessageSentEvent, _super);
    function MessageSentEvent(to, from, message) {
        var _this = _super.call(this) || this;
        _this.to = to;
        _this.from = from;
        _this.message = message;
        return _this;
    }
    return MessageSentEvent;
}(ASEvent));
exports.MessageSentEvent = MessageSentEvent;
/**
 * MessageDroppedEvent
 */
var MessageDroppedEvent = (function (_super) {
    __extends(MessageDroppedEvent, _super);
    function MessageDroppedEvent() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return MessageDroppedEvent;
}(MessageSentEvent));
exports.MessageDroppedEvent = MessageDroppedEvent;
/**
 * MessageAcceptedEvent
 */
var MessageAcceptedEvent = (function (_super) {
    __extends(MessageAcceptedEvent, _super);
    function MessageAcceptedEvent() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return MessageAcceptedEvent;
}(MessageSentEvent));
exports.MessageAcceptedEvent = MessageAcceptedEvent;
/**
 * MessageReceivedEvent
 */
var MessageReceivedEvent = (function (_super) {
    __extends(MessageReceivedEvent, _super);
    function MessageReceivedEvent() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return MessageReceivedEvent;
}(MessageSentEvent));
exports.MessageReceivedEvent = MessageReceivedEvent;
/**
 * ReceiveStartedEvent
 */
var ReceiveStartedEvent = (function (_super) {
    __extends(ReceiveStartedEvent, _super);
    function ReceiveStartedEvent(path) {
        var _this = _super.call(this) || this;
        _this.path = path;
        return _this;
    }
    return ReceiveStartedEvent;
}(ASEvent));
exports.ReceiveStartedEvent = ReceiveStartedEvent;
/**
 * SelectStartedEvent
 */
var SelectStartedEvent = (function (_super) {
    __extends(SelectStartedEvent, _super);
    function SelectStartedEvent() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return SelectStartedEvent;
}(ReceiveStartedEvent));
exports.SelectStartedEvent = SelectStartedEvent;
/**
 * ActorRemovedEvent
 */
var ActorRemovedEvent = (function (_super) {
    __extends(ActorRemovedEvent, _super);
    function ActorRemovedEvent(path, code) {
        var _this = _super.call(this) || this;
        _this.path = path;
        _this.code = code;
        return _this;
    }
    return ActorRemovedEvent;
}(ASEvent));
exports.ActorRemovedEvent = ActorRemovedEvent;
//# sourceMappingURL=Events.js.map